input ingredients_insert_input {
    description: String
    title: String
    image: String
}

input ingredients_set_input {
    description: String
    title: String
    image: String
}

"The `Upload` scalar type represents a multipart file upload."
scalar Upload

"The `File` type, represents the response of uploading a file."
type File {
    id: Int!
    name: String!
    content: String!
}

query FindAllIngredients {
    ingredients {
        id
        description
        title
        image
    }
}

query FindIngredientWithID($id: String!) {
    ingredients(where: { id: { _eq: $id } }) {
        id
        description
        title
        image
    }
}

mutation UpdateIngredient($id: String!, $ingredient: ingredients_set_input!) {
    update_ingredients(where: { id: { _eq: $id } }, _set: $ingredient) {
        returning {
            id
            description
            title
            image
        }
    }
}

mutation CreateIngredient($ingredient: ingredients_insert_input!) {
    insert_ingredients(objects: [$ingredient]) {
        returning {
            id
        }
    }
}

mutation DeleteIngredient($id: String!) {
    delete_ingredients(where: { id: { _eq: $id } }) {
        affected_rows
    }
}
