input IngredientInput {
    description: String
    title: String
    image: String
    measurementType: String
}

"The `Upload` scalar type represents a multipart file upload."
scalar Upload

"The `File` type, represents the response of uploading a file."
type File {
    id: Int!
    name: String!
    content: String!
}

query FindAllIngredients {
    ingredients {
        id
        description
        title
        image
        measurementType
    }
}

query FindIngredientWithID($id: String!) {
    ingredient(id: $id) {
        id
        description
        title
        image
        measurementType
    }
}

mutation UpdateIngredient($id: ID!, $ingredient: IngredientInput!) {
    updateIngredient(id: $id, ingredient: $ingredient) {
        id
        description
        title
        image
        measurementType
    }
}

mutation CreateIngredient($ingredient: IngredientInput!) {
    createIngredient(ingredient: $ingredient) {
        id
        description
        title
        image
        measurementType
    }
}

mutation DeleteIngredient($id: ID!) {
    deleteIngredient(id: $id)
}

mutation UploadFiles($files: [Upload!]!) {
    uploadFiles(files: $files) {
        id
    }
}
