query FindAllIngredients {
    ingredients {
        id
        description
        title
        image
        measurementType
    }
}

query FindIngredientWithID($id: String!) {
    ingredient(id: $id) {
        id
        description
        title
        image
        measurementType
    }
}
