input IngredientInput {
    description: String
    title: String
    image: String
    measurementType: String
}

query FindAllIngredients {
    ingredients {
        id
        description
        title
        image
        measurementType
    }
}

query FindIngredientWithID($id: String!) {
    ingredient(id: $id) {
        id
        description
        title
        image
        measurementType
    }
}

mutation UpdateIngredient($id: ID!, $ingredient: IngredientInput!) {
    updateIngredient(id: $id, ingredient: $ingredient) {
        id
        description
        title
        image
        measurementType
    }
}
