# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    
    - name: Build project
      run: npm run build --if-present
    
    - name: Running tests
      run: npm test
      env:
        CI: true

    - name: List output files
      run: ls

    - name: Create SSH folder for deploy key
      run: mkdir "$HOME/.ssh"
    - name: Create SSH private key
      run: echo "${{ secrets.ftp_private_key }}" >> "$HOME/.ssh/ftp_key"
    - name: Create SSH public key
      run: echo "${{ secrets.ftp_public_key }}" >> "$HOME/.ssh/ftp_key.pub"
    
    - run: ping ns12.inleed.net -c 4
    
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://185.189.51.191:2020/${{ secrets.ftp_path }}
        ftp-username: ${{ secrets.ftp_username }}
        ftp-password: test123
        known_hosts: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCs4TnYwvvAXnLBx5Vg/z3i9U7DZlFsbsA1VOhEpegbJP0cz9INdD7GblAkfOR/9u6HxesOfN13GOEXSBf0I9Nhtw/czoRAipSu+jmMTcoQ+JRe5DU2b3mNjewBpYgFwKj3b3V59MfhCPuQbsEesAeokpZEnxmEp6dJrYw2bqatCBZfcFfJe6330yLOUSuJ4igdFFYw/hiCzV5q9QQyYpWuM1raavIOVapEEmfT1NO/64QzQzroqZDywrVU7iCBGfd5sTUnpLm3qAlMWOXEEp5VbfQQEiX00AufvdfdD7c8BXQ34eabPcaqMlAajc5cG0lSKP7RxD7oJ1yDUqXxjWir"
        local-dir: dist
        git-ftp-args: --insecure --key "$HOME/.ssh/ftp_key" --pubkey "$HOME/.ssh/ftp_key.pub"
