# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    
    - name: Build project
      run: npm run build --if-present
    
    - name: Running tests
      run: npm test
      env:
        CI: true

    - name: Create SSH folder for deploy key
      run: mkdir "$HOME/.ssh"
      
    - name: Create SSH private key
      run: echo "${{ secrets.ftp_private_key }}" >> "$HOME/.ssh/ftp_key"

    - name: Create SSH public key
      run: echo "${{ secrets.ftp_public_key }}" >> "$HOME/.ssh/ftp_key.pub"
    
    - run: ls -al
    - run: ls -al dist
    
    - name: Uploading files
      run: git ftp push --force --auto-init --verbose --user ${{ secrets.ftp_username }} --passwd ${{ secrets.ftp_password }} --syncroot ./dist --insecure --key $HOME/.ssh/ftp_key --pubkey $HOME/.ssh/ftp_key.pub sftp://185.189.51.191:2020${{ secrets.ftp_path }}
